[project]
name = "discord"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord.py",
    "requests",
    "aiohttp",
    "pydantic",
    "pydantic-settings",
    "openai>=3.19.2",
    "trafilatura>=2.2.0",
    "ddgs>=9.16.0",
]
